goog.provide("epiviz.ui.controls.MeasurementsDialogData");epiviz.ui.controls.MeasurementsDialogData=function(measurements,type,datasource,datasourceGroup,dataprovider,annotation,defaultChartType,minSelectedMeasurements){this.measurements=measurements;this.type=type;this.datasource=datasource;this.datasourceGroup=datasourceGroup;this.dataprovider=dataprovider;this.annotation=annotation;this.defaultChartType=defaultChartType;this.minSelectedMeasurements=minSelectedMeasurements||1};goog.provide("epiviz.ui.controls.DataTable");
epiviz.ui.controls.DataTable=function(container,columns,rows,rowParser,multiselect,showColumnSelector){epiviz.ui.controls.Control.call(this,container);this._columns=columns;this._rows=rows;this._rowsArray=[];var self=this;this._rows.foreach(function(row){self._rowsArray.push(row)});this._rowParser=rowParser;this._multiselect=multiselect||false;this._showColumnSelector=showColumnSelector||false;this._table=null;this._columnSelector=null;this._selectedIndices=[];this._selectedIndicesMap={};this._selectList=
null;this._deselectList=null;this._lastSelection=null};epiviz.ui.controls.DataTable.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Control.prototype);epiviz.ui.controls.DataTable.constructor=epiviz.ui.controls.DataTable;epiviz.ui.controls.DataTable.ColumnType={STRING:"string",NUMBER:"number",BOOLEAN:"boolean"};
epiviz.ui.controls.DataTable.prototype.initialize=function(){this._container.append('<div class="epiviz-data-table"><table style="width: 100%!important;"><thead></thead><tbody></tbody><tfoot></tfoot></table></div>');this._table=this._container.find("table");var thead=this._table.find("thead");var tfoot=this._table.find("tfoot");var tbody=this._table.find("tbody");var headFootContent=sprintf("<tr><th>%s</th></tr>",this._columns.join("</th><th>"));thead.append(headFootContent);tfoot.append(headFootContent);
var self=this;this._rows.foreach(function(row){var rowHtml="";for(var i=0;i<self._columns.length;++i)rowHtml+=sprintf("<td>%s</td>",self._rowParser(row,self._columns[i]));tbody.append(sprintf("<tr>%s</tr>",rowHtml))});var j;var columnFilterTypes=new Array(this._columns.length);for(j=0;j<this._columns.length;++j)columnFilterTypes[j]={type:"text",bRegex:true,bSmart:true};this._table.dataTable({bJQueryUI:true,sDom:'<"H"lfr>Tt<"F"ip>',oTableTools:{sRowSelect:this._multiselect?"multi":"single",aButtons:[],
fnPreRowSelect:function(e,nodes,isSelect){return self._preRowSelect(this,e,nodes,isSelect)},fnRowSelected:function(nodes){return self._select(this,nodes)},fnRowDeselected:function(nodes){return self._select(this,nodes)}}}).columnFilter({aoColumns:columnFilterTypes});var visibleIndex=-1;for(j=0;j<this._columns.length;++j){if(this._columns[j].isVisible)++visibleIndex;this._table.fnSetColumnVis(j,this._columns[j].isVisible);if(!this._columns[j].defaultFilter)continue;this._table.fnFilter(sprintf("(%s)|any",
this._columns[j].defaultFilter),j,true,true);this._table.find("tfoot").find(sprintf("th:eq(%s)",visibleIndex)).find("input").removeClass("search_init").val(sprintf("(%s)|any",this._columns[j].defaultFilter))}this._container.find(".ui-buttonset").first().attr("style","position: absolute!important;");if(this._showColumnSelector){var colSelectorCls="epiviz-data-table-column-selector";this._container.find(".fg-toolbar").first().append(sprintf('<div style="float: right; margin-right: 5px;">'+"<label>Selected Columns: </label>"+
'<select class="%s" multiple="multiple" style="">'+'<option value="-1">All</option>'+"</select>"+"</div>",colSelectorCls));this._columnSelector=this._container.find("."+colSelectorCls);for(var i=0;i<this._columns.length;++i){var option=sprintf('<option value="%s"%s%s>%s</option>',i,this._columns[i].isVisible?' selected="selected"':"",this._columns[i].isFixed?' disabled="disabled"':"",this._columns[i].name);this._columnSelector.append(option)}this._columnSelector.dropdownchecklist({width:"80px",firstItemChecksAll:true,
onComplete:function(selector){self._selectColumns(selector)}})}};epiviz.ui.controls.DataTable.prototype.selectedIndices=function(){return this._selectedIndices||[]};epiviz.ui.controls.DataTable.prototype.selectedRows=function(){if(!this._selectedIndices)return[];var result=new Array(this._selectedIndices.length);for(var i=0;i<this._selectedIndices.length;++i)result[i]=this._rowsArray[this._selectedIndices[i]];return result};
epiviz.ui.controls.DataTable.prototype._preRowSelect=function(tableTools,e,nodes,isSelect){if(e){this._selectList=this._deselectList=null;if(e.shiftKey&&nodes.length==1){this._deselectList=tableTools.fnGetSelected();if(!this._lastSelection)this._lastSelection=nodes[0];this._selectList=this._getRangeOfRows(this._lastSelection,nodes[0])}else{this._lastSelection=nodes[0];if(!e.ctrlKey&&!e.metaKey){this._deselectList=tableTools.fnGetSelected();if(!isSelect)this._selectList=nodes}}}return true};
epiviz.ui.controls.DataTable.prototype._getRangeOfRows=function(fromNode,toNode){var fromPos=this._table.fnGetPosition(fromNode),toPos=this._table.fnGetPosition(toNode),oSettings=this._table.fnSettings(),fromIndex=$.inArray(fromPos,oSettings.aiDisplay),toIndex=$.inArray(toPos,oSettings.aiDisplay),result=[];if(fromIndex>=0&&toIndex>=0)for(var i=Math.min(fromIndex,toIndex);i<=Math.max(fromIndex,toIndex);++i){var dataIndex=oSettings.aiDisplay[i];result.push(oSettings.aoData[dataIndex].nTr)}return result.length>
0?result:null};
epiviz.ui.controls.DataTable.prototype._select=function(tableTools,nodes){var nodeList;if(this._deselectList){nodeList=this._deselectList;this._deselectList=null;tableTools.fnDeselect(nodeList)}if(this._selectList){nodeList=this._selectList;if(!this._multiselect&&nodeList.length>0)nodeList=[nodeList[nodeList.length-1]];this._selectList=null;tableTools.fnSelect(nodeList)}var selection=tableTools.fnGetSelected();var selectedIndices=new Array(selection.length);var selectedIndicesMap={};var i;for(i=0;i<
selection.length;++i){selectedIndices[i]=this._table.fnGetPosition(selection[i]);selectedIndicesMap[selectedIndices[i]]=true}for(i=0;i<this._selectedIndices.length;++i)if(!selectedIndicesMap[this._selectedIndices[i]]){delete this._selectedIndicesMap[this._selectedIndices[i]];this._selectedIndices.splice(i,1);--i}for(i=0;i<selectedIndices.length;++i)if(!this._selectedIndicesMap[selectedIndices[i]]){this._selectedIndicesMap[selectedIndices[i]]=true;this._selectedIndices.push(selectedIndices[i])}return true};
epiviz.ui.controls.DataTable.prototype._selectColumns=function(selector){var selectedIndices={},i;for(i=0;i<selector.options.length;++i)if(selector.options[i].selected&&selector.options[i].value)selectedIndices[parseInt(selector.options[i].value)]=true;for(i=0;i<this._columns.length;++i)this._table.fnSetColumnVis(i,selectedIndices[i]||this._columns[i].isFixed)};goog.provide("epiviz.ui.controls.DataTable.Column");
epiviz.ui.controls.DataTable.Column=function(id,name,type,isHidden,isFixed,defaultFilter){this.id=id;this.name=name;this.type=type;this.isVisible=!isHidden;this.isFixed=isFixed||false;this.defaultFilter=defaultFilter||""};epiviz.ui.controls.DataTable.Column.prototype.toString=function(){return this.name};goog.provide("epiviz.ui.controls.Wizard");epiviz.ui.controls.Wizard=function(title,handlers,steps,initialData,width,height,showTabs){epiviz.ui.controls.Dialog.call(this,title,handlers);this._steps=steps;this._initialData=initialData;this._width=width;this._height=height;this._showTabs=showTabs||false;this._tabs=null;this._initialize()};epiviz.ui.controls.Wizard.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);epiviz.ui.controls.Wizard.constructor=epiviz.ui.controls.Wizard;
epiviz.ui.controls.Wizard.prototype._initialize=function(){var self=this;this._dialog=$("#"+this._id);this._dialog.append('<div class="wizard-dialog">'+'<div class="wizard-tabs">'+'<ul class="wizard-tabs-title-list"></ul>'+"</div>"+"</div>");this._tabs=this._dialog.find(".wizard-tabs");var titleList=this._tabs.find(".wizard-tabs-title-list");for(var i=0;i<this._steps.length;++i){titleList.append(sprintf('<li><a href="#%s-tab-%s">%s</a></li>',this._id,i,this._steps[i].title()));this._tabs.append(sprintf('<div id="%s-tab-%s"></div>',
this._id,i))}if(!this._showTabs){titleList.css("visibility","hidden");titleList.css("position","absolute")}this._tabs.tabs({activate:function(e,ui){self._tabActivate(ui)},disabled:epiviz.utils.range(this._steps.length-1,1)});this._dialog.dialog({autoOpen:false,resizable:true,width:this._width||undefined,height:this._height||undefined,buttons:{Back:function(){var selectedTabIndex=self._tabs.tabs("option","active");if(selectedTabIndex==0)return;self._tabs.tabs("option","disabled",epiviz.utils.range(self._steps.length-
selectedTabIndex,selectedTabIndex));self._tabs.tabs("option","active",selectedTabIndex-1)},Next:function(){var selectedTabIndex=self._tabs.tabs("option","active");var result=self._steps[selectedTabIndex].next();if(result.error){var errorDialog=new epiviz.ui.controls.MessageDialog("Error",{Ok:function(){}},result.error,epiviz.ui.controls.MessageDialog.Icon.ERROR);errorDialog.show();return}self._steps[selectedTabIndex+1].initialize($(sprintf("#%s-tab-%s",self._id,selectedTabIndex+1)),result.data);self._tabs.tabs("option",
"disabled",epiviz.utils.range(self._steps.length-selectedTabIndex-2,selectedTabIndex+2));self._tabs.tabs("option","active",selectedTabIndex+1)},Finish:function(){var result=self._steps[self._steps.length-1].next();if(result.error){var errorDialog=new epiviz.ui.controls.MessageDialog("Error",{Ok:function(){}},result.error,epiviz.ui.controls.MessageDialog.Icon.ERROR);errorDialog.show();return}if(self._handlers.finish)self._handlers.finish(result.data);$(this).dialog("close")},Cancel:function(){if(self._handlers.close)self._handlers.close();
$(this).dialog("close")}},modal:true});if(this._steps.length>1){this._dialog.parent().find('button:contains("Finish")').button("disable");this._dialog.parent().find('button:contains("Next")').button("enable")}else{this._dialog.parent().find('button:contains("Finish")').button("enable");this._dialog.parent().find('button:contains("Next")').button("disable")}this._steps[0].initialize($(sprintf("#%s-tab-0",self._id)),this._initialData)};
epiviz.ui.controls.Wizard.prototype._tabActivate=function(ui){var selectedTabIndex=this._tabs.tabs("option","active");var finishButton=this._dialog.parent().find('button:contains("Finish")');var nextButton=this._dialog.parent().find('button:contains("Next")');if(selectedTabIndex==this._steps.length-1){nextButton.button("disable");finishButton.button("enable")}else{nextButton.button("enable");finishButton.button("disable")}this._tabs.tabs("option","disabled",epiviz.utils.range(this._steps.length-selectedTabIndex-
1,selectedTabIndex+1))};epiviz.ui.controls.Wizard.prototype.show=function(){var self=this;this._dialog.dialog("open");this._dialog.dialog("option","position","center");this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null}})};goog.provide("epiviz.ui.controls.Wizard.Step");epiviz.ui.controls.Wizard.Step=function(){};epiviz.ui.controls.Wizard.Step.prototype.initialize=function(container,data){};epiviz.ui.controls.Wizard.Step.prototype.next=function(){};
epiviz.ui.controls.Wizard.Step.prototype.title=function(){};goog.provide("epiviz.ui.controls.DatasourceGroupWizardStep");epiviz.ui.controls.DatasourceGroupWizardStep=function(){this._dataTable=null;this._data=null};
epiviz.ui.controls.DatasourceGroupWizardStep.prototype.initialize=function(container,data){this._data=data;container.find(".epiviz-data-table").remove();var columns=[new epiviz.ui.controls.DataTable.Column("datasourceGroup","Data Source Group",epiviz.ui.controls.DataTable.ColumnType.STRING)];var datasourceGroups={};data.measurements.foreach(function(m){if(data.type&&data.type!=m.type())return;if(data.dataprovider&&data.dataprovider!=m.dataprovider())return;if(data.annotation)for(var key in data.annotation){if(!data.annotation.hasOwnProperty(key))continue;
if(!m.annotation()||m.annotation()[key]!=data.annotation[key])return}datasourceGroups[m.datasourceGroup()]=true});this._dataTable=new epiviz.ui.controls.DataTable(container,columns,new epiviz.utils.IterableArray(Object.keys(datasourceGroups)),function(v){return v});this._dataTable.initialize()};
epiviz.ui.controls.DatasourceGroupWizardStep.prototype.next=function(){var selectedRows=this._dataTable?this._dataTable.selectedRows():[];if(selectedRows.length==0)return{error:"No rows selected"};this._data.datasourceGroup=selectedRows[0];return{data:this._data}};epiviz.ui.controls.DatasourceGroupWizardStep.prototype.title=function(){return"Select Datasource Group"};goog.provide("epiviz.ui.controls.MeaurementsWizardStep");epiviz.ui.controls.MeaurementsWizardStep=function(){this._dataTable=null;this._data=null;this._measurements=null};
epiviz.ui.controls.MeaurementsWizardStep.prototype.initialize=function(container,data){this._data=data;container.find(".epiviz-data-table").remove();var ColumnType=epiviz.ui.controls.DataTable.ColumnType;var columns=[new epiviz.ui.controls.DataTable.Column("id","Id",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("name","Name",ColumnType.STRING,false,true),new epiviz.ui.controls.DataTable.Column("defaultChartType","Default Chart Type",ColumnType.STRING,false,true,data.defaultChartType||
""),new epiviz.ui.controls.DataTable.Column("type","Type",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("datasourceId","Data Source",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("datasourceGroup","Data Source Group",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("dataprovider","Data Provider",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("formulaStr","Formula",ColumnType.STRING,true),new epiviz.ui.controls.DataTable.Column("annotation",
"Annotation",ColumnType.STRING)];this._measurements=data.measurements.subset(function(m){if(data.type&&data.type!=m.type())return false;if(data.datasource&&data.datasource!=m.datasourceId())return false;if(data.datasourceGroup&&data.datasourceGroup!=m.datasourceGroup())return false;if(data.dataprovider&&data.dataprovider!=m.dataprovider())return false;if(data.annotation)for(var key in data.annotation){if(!data.annotation.hasOwnProperty(key))continue;if(!m.annotation()||m.annotation()[key]!=data.annotation[key])return false}return true});
if(data.type&&data.type==epiviz.measurements.Measurement.Type.RANGE){var self=this;var datasourceGroupMap={};data.measurements.foreach(function(m){if(m.type()==epiviz.measurements.Measurement.Type.RANGE||m.datasourceGroup()in datasourceGroupMap||m.isComputed())return;self._measurements.add(m.datasource());datasourceGroupMap[m.datasourceGroup()]=true})}this._dataTable=new epiviz.ui.controls.DataTable(container,columns,this._measurements,function(m,column){var result=null;switch(column.id){case "annotation":result=
epiviz.utils.mapJoin(m.annotation(),": ","<br />");break;default:result=m[column.id]();break}if(result===0||result===""||result)return result;return""},true,true);this._dataTable.initialize()};
epiviz.ui.controls.MeaurementsWizardStep.prototype.next=function(){var selectedRows=this._dataTable?this._dataTable.selectedRows():[];if(selectedRows.length<this._data.minSelectedMeasurements)return{error:"Minimum selected rows required is "+this._data.minSelectedMeasurements};var selectedMeasurements=new epiviz.measurements.MeasurementSet;for(var i=0;i<selectedRows.length;++i)selectedMeasurements.add(selectedRows[i]);this._data.measurements=selectedMeasurements;return{data:this._data}};
epiviz.ui.controls.MeaurementsWizardStep.prototype.title=function(){return"Select Measurements"};goog.provide("epiviz.ui.controls.MessageDialog");epiviz.ui.controls.MessageDialog=function(title,handlers,message,icon){epiviz.ui.controls.Dialog.call(this,title,handlers);this._message=message;this._icon=icon||epiviz.ui.controls.MessageDialog.Icon.INFO};epiviz.ui.controls.MessageDialog.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);epiviz.ui.controls.MessageDialog.constructor=epiviz.ui.controls.MessageDialog;epiviz.ui.controls.MessageDialog.Icon={INFO:"info",ERROR:"error",QUESTION:"question"};
epiviz.ui.controls.MessageDialog.prototype.show=function(){epiviz.ui.controls.Dialog.prototype.show.call(this);var Icon=epiviz.ui.controls.MessageDialog.Icon;if(!this._dialog){var self=this;this._dialog=$("#"+this._id);this._dialog.css("display","inline");var state=this._icon==Icon.ERROR?"error":"highlight";var icon=this._icon==Icon.ERROR?"alert":"info";this._dialog.append(sprintf('<div class="ui-state-%s ui-corner-all" style="margin: 5px; padding: 5px; height: auto;">'+'<div class="ui-icon ui-icon-%s" style="float: left; margin-right: 5px;"></div>'+
'<div class="dialog-text">%s</div>'+"</div>",state,icon,this._message));var buttons={};for(var buttonName in this._handlers){if(!this._handlers.hasOwnProperty(buttonName))continue;(function(buttonName){buttons[buttonName]=function(){self._handlers[buttonName]();$(this).dialog("close")}})(buttonName)}this._dialog.dialog({autoOpen:false,resizable:false,buttons:buttons,modal:true});this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null}})}this._dialog.dialog("open");this._dialog.dialog("option",
"position","center")};goog.provide("epiviz.ui.controls.ColorPickerDialog");
epiviz.ui.controls.ColorPickerDialog=function(handlers,colors){epiviz.ui.controls.Dialog.call(this,"Pick Colors",handlers);this._dialog=$("#"+this._id);this._dialog.append('<div class="color-picker-form" action="" style="width: 420px;">'+'<div class="chart-picker" style="float: right;"></div>'+"</div>");this._initialColors=colors;this._colors=colors;var colorPickerForm=this._dialog.find(".color-picker-form");var tableContent="";for(var i=0;i<this._colors.length;++i){var inputClass=sprintf("color-%s",
i);tableContent+=sprintf("<tr>"+"<td><label>%s:&nbsp;</label></td>"+'<td><input type="text" name="%s" class="colorwell %s" value="%s" /></td>'+"</tr>",colors[i].name,inputClass,inputClass,this._colors[i].color)}colorPickerForm.append(sprintf('<table class="color-picker-table">%s</table>',tableContent));var f=$.farbtastic(sprintf("#%s .chart-picker",this._id));var p=$(sprintf("#%s .chart-picker",this._id)).css("opacity",.25);var selected;$(sprintf("#%s .colorwell",this._id)).each(function(){f.linkTo(this);
$(this).css("opacity",.75)}).focus(function(){if(selected)$(selected).css("opacity",.75).removeClass("colorwell-selected");f.linkTo(this);p.css("opacity",1);$(selected=this).css("opacity",1).addClass("colorwell-selected")});var self=this;this._dialog.dialog({autoOpen:false,resizable:false,width:"440",buttons:{Ok:function(){var inputs=colorPickerForm.find(".colorwell");for(var i=0;i<inputs.length;++i)self._colors[i].color=inputs[i].value;self._handlers.ok(self._colors);$(this).dialog("close")},Cancel:function(){self._handlers.cancel();
$(this).dialog("close")},Reset:function(){self._colors=self._initialColors;for(var i=0;i<self._colors.length;++i){var inputClass=sprintf(".color-%s",i);f.linkTo($(sprintf("#%s %s",self._id,inputClass)));f.setColor(self._colors[i].color);++i}if(selected)f.linkTo(selected);self._handlers.reset()}},modal:true})};epiviz.ui.controls.ColorPickerDialog.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);epiviz.ui.controls.ColorPickerDialog.constructor=epiviz.ui.controls.ColorPickerDialog;
epiviz.ui.controls.ColorPickerDialog.prototype.show=function(){epiviz.ui.controls.Dialog.prototype.show.call(this);var self=this;if(this._dialog){this._dialog.dialog("open");this._dialog.dialog("option","position","center");this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null}})}};goog.provide("epiviz.ui.controls.SaveSvgAsImageDialog");
epiviz.ui.controls.SaveSvgAsImageDialog=function(handlers,chartId,chartSaverLocation){epiviz.ui.controls.Dialog.call(this,"Save Chart SVG as Image",handlers);this._dialog=$("#"+this._id);this._dialog.append('<div class="save-svg-dialog">'+'<label class="dialog-label">Choose file format:</label>'+"<br/><br/>"+'<div style="position:absolute; right:15px;">'+'<select class="svg-file-format">'+'<option value="pdf" selected="selected">PDF</option>'+'<option value="ps" >PS</option>'+'<option value="png" >PNG</option>'+
'<option value="svg">SVG</option>'+'<option value="eps">EPS</option>'+"</select>"+"</div>"+sprintf('<form name="%s-svg-save-form" method="POST">',this._id)+"<div>"+'<input type="hidden" name="svg" />'+'<input type="hidden" name="format" />'+"<br/><br/>"+"</div>"+"</form>"+"</div>");this._chartId=chartId;this._chartSaverLocation=chartSaverLocation;var self=this;this._dialog.dialog({autoOpen:false,resizable:false,width:"200",buttons:{Ok:function(){var svg=$("#"+self._chartId).find("svg").clone();svg.attr("xmlns",
"http://www.w3.org/2000/svg");svg.attr("version","1.1");var fileFormat=self._dialog.find(".svg-file-format");var form=document.forms[sprintf("%s-svg-save-form",self._id)];form.action=self._chartSaverLocation;form["svg"].value=$("<div>").append(svg).html();form["format"].value=fileFormat.val();form.submit();self._handlers.ok();$(this).dialog("close")},Cancel:function(){self._handlers.cancel();$(this).dialog("close")}},modal:true})};epiviz.ui.controls.SaveSvgAsImageDialog.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);
epiviz.ui.controls.SaveSvgAsImageDialog.constructor=epiviz.ui.controls.SaveSvgAsImageDialog;epiviz.ui.controls.SaveSvgAsImageDialog.prototype.show=function(){epiviz.ui.controls.Dialog.prototype.show.call(this);var self=this;if(this._dialog){this._dialog.dialog("open");this._dialog.dialog("option","position","center");this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null}})}};goog.provide("epiviz.ui.controls.ComputedMeasurementsDialog");
epiviz.ui.controls.ComputedMeasurementsDialog=function(title,handlers,measurements,chartsMeasurements){epiviz.ui.controls.Dialog.call(this,title,handlers);this._measurements=measurements;this._chartsMeasurements=chartsMeasurements;this._expressionTextBox=null;this._idTextBox=null;this._nameTextBox=null;this._minTextBox=null;this._maxTextBox=null;this._measurementsList=null;this._addButtonProperties={text:false,icons:{primary:"ui-icon ui-icon-plus"}};this._deleteButtonsProperties={text:false,icons:{primary:"ui-icon ui-icon-trash"}};
this._tabs=null;this._selectedDatasourceGroup=null;this._datasourceGroupMeasurements=null;this._addTabs();this._addDialogContents();this._addDatasourceGroupTable(measurements)};epiviz.ui.controls.ComputedMeasurementsDialog.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);epiviz.ui.controls.ComputedMeasurementsDialog.constructor=epiviz.ui.controls.ComputedMeasurementsDialog;
epiviz.ui.controls.ComputedMeasurementsDialog.prototype.show=function(){epiviz.ui.controls.Dialog.prototype.show.call(this);var self=this;if(this._dialog){this._dialog.dialog("open");this._dialog.dialog("option","position","center");this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null;self._handlers.close()}})}};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._addDatasourceGroupTable=function(measurements){var self=this;var container=$(sprintf("#datasource-group-tab-%s",this._id));var rawTableCls="computed-measurements-dialog-raw-table";var table="<table "+'style="border-spacing:0; '+"border-collapse:collapse; "+"-webkit-touch-callout: none; "+"-webkit-user-select: none; "+"-khtml-user-select: none; "+"-moz-user-select: moz-none; "+"-ms-user-select: none; "+"user-select: none; "+'width: 100%%;" '+
'class="'+rawTableCls+'">%s</table>';var header="<thead><tr><th>Data Source Group</th></tr></thead>";var footer="<tfoot><tr><th>Data Source Group</th></tr></tfoot>";var body="";var measurementsByDatasourceGroup={};measurements.foreach(function(m){if(m.type()!=epiviz.measurements.Measurement.Type.FEATURE)return;if(!(m.datasourceGroup()in measurementsByDatasourceGroup))measurementsByDatasourceGroup[m.datasourceGroup()]=[];measurementsByDatasourceGroup[m.datasourceGroup()].push(m)});for(var g in measurementsByDatasourceGroup){if(!measurementsByDatasourceGroup.hasOwnProperty(g))continue;
body+=sprintf('<tr><td class="center">%s</td></tr>',g)}container.append(sprintf(table,header+body+footer));var rawTable=container.find("."+rawTableCls);var oTable=rawTable.dataTable({bJQueryUI:true,sDom:'<"H"lfr>Tt<"F"ip>',"oTableTools":{"sRowSelect":"single","aButtons":[],"fnPreRowSelect":function(e,nodes,isSelect){return true},"fnRowSelected":function(nodes){var data=oTable.fnGetData(nodes[0]);self._selectedDatasourceGroup=data[0];self._datasourceGroupMeasurements=measurementsByDatasourceGroup[self._selectedDatasourceGroup]},
"fnRowDeselected":function(nodes){var data=oTable.fnGetData(nodes[0]);if(data==self._selectedDatasourceGroup){self._selectedDatasourceGroup=null;self._datasourceGroupMeasurements=null}}}});container.find(".DTTT_container").css("position","absolute")};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._addTabs=function(){var self=this;this._selectDialog().append('<div class="computed-measurements-dialog">'+'<div class="computed-measurements-tabs">'+"<ul>"+sprintf('<li><a href="#datasource-group-tab-%s">Data Source Group</a></li>',this._id)+sprintf('<li><a href="#formula-tab-%s">Expression</a></li>',this._id)+"</ul>"+sprintf('<div id="datasource-group-tab-%s"></div>',this._id)+sprintf('<div id="formula-tab-%s"></div>',this._id)+"</div>"+"</div>");
this._tabs=this._selectTabs();this._tabs.tabs({activate:function(e,ui){self._tabActivate(ui)}})};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._addDialogContents=function(){var self=this;this._selectDialog().dialog({autoOpen:false,resizable:true,width:"600",height:"550",buttons:{Back:function(){var selectedTabIndex=self._tabs.tabs("option","active");if(selectedTabIndex==0)return;self._tabs.tabs("option","active",0)},Next:function(){var selectedTabIndex=self._tabs.tabs("option","active");if(selectedTabIndex==1)return;self._tabs.tabs("option","active",1)},Add:function(){var expr=epiviz.utils.ExpressionParser.parse(self._selectExpressionTextBox().val().trim());
var referredMeasurements={};var variables=expr.variables();var min=null,max=null;var metadata=[];var usedMetadata={};for(var i=0;i<variables.length;++i){var variable=variables[i];if(!epiviz.utils.stringStartsWith(variable,"{")||!epiviz.utils.stringEndsWith(variable,"}"))continue;var index=parseInt(variable.substring(1,variable.length-1));var m=self._datasourceGroupMeasurements[index];referredMeasurements[index]=m;if(min===null||min>m.minValue())min=m.minValue();if(max===null||max<m.maxValue())max=
m.maxValue();if(m.metadata())for(var j=0;j<m.metadata().length;++j)if(!usedMetadata[m.metadata()[j]]){usedMetadata[m.metadata()[j]]=true;metadata.push(m.metadata()[j])}}var userMin=self._selectMinTextBox().val().trim();var userMax=self._selectMaxTextBox().val().trim();min=userMin?parseFloat(userMin):min;max=userMax?parseFloat(userMax):max;var id=self._selectIdTextBox().val().trim()||epiviz.utils.generatePseudoGUID(5);var measurement=new epiviz.measurements.Measurement(id,self._selectNameTextBox().val().trim()||
"Unnamed ["+id+"]",epiviz.measurements.Measurement.Type.FEATURE,null,self._selectedDatasourceGroup,null,{referredMeasurements:referredMeasurements,expression:expr},"any",null,min,max,metadata);var nextIndex=self._datasourceGroupMeasurements.length;var msList=$(sprintf("#computed-measurement-measurements-%s",self._id));var removeButton='<button id="delete-button-%2$s-%3$s" data-measurement="%2$s">Delete</button>';msList.append(sprintf('<div style="min-height: 30px; padding: 2px;">'+'<div style="margin: 6px; float: left;">%1$s {<b>%2$s</b>}</div>'+
'<div style="float: right;">'+removeButton+'<button style="" id="measurement-button-%2$s-%3$s" data-measurement="%2$s">Insert %2$s</button>'+"</div>"+"</div>",measurement.name(),nextIndex,self._id));$("#measurement-button-"+nextIndex+"-"+self._id).button(self._addButtonProperties).click(function(){self._addButtonClick($(this))});$("#delete-button-"+nextIndex+"-"+self._id).button(self._deleteButtonsProperties).click(function(){self._deleteButtonClick($(this))});self._datasourceGroupMeasurements.push(measurement);
self._handlers.add(measurement)},Close:function(){self._handlers.close();$(this).dialog("close")}},modal:true})};epiviz.ui.controls.ComputedMeasurementsDialog.prototype._addButtonClick=function(button){var measurementIndex=button.data("measurement");var exprBox=this._selectExpressionTextBox();exprBox.val(exprBox.val().trim()+" {"+measurementIndex+"}")};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._deleteButtonClick=function(button){var measurementIndex=button.data("measurement");var measurement=this._datasourceGroupMeasurements[measurementIndex];var dialog;for(var i=0;i<this._datasourceGroupMeasurements.length;++i){var m=this._datasourceGroupMeasurements[i];if(m==null||m===measurement||!m.isComputed())continue;if(m.componentMeasurements().contains(measurement)){dialog=new epiviz.ui.controls.MessageDialog("Measurement cannot be deleted",
{Ok:function(){}},"There are other measurements that depend on the one selected. Please delete those before deleting this.",epiviz.ui.controls.MessageDialog.Icon.ERROR);dialog.show();return}}for(var chartId in this._chartsMeasurements){if(!this._chartsMeasurements.hasOwnProperty(chartId))continue;if(this._chartsMeasurements[chartId].contains(measurement)){dialog=new epiviz.ui.controls.MessageDialog("Measurement cannot be deleted",{Ok:function(){}},"There are charts using the selected measurement. Remove them from the workspace and then try again.",
epiviz.ui.controls.MessageDialog.Icon.ERROR);dialog.show();return}}this._datasourceGroupMeasurements[measurementIndex]=null;button.parent().parent().remove();this._handlers.remove(measurement)};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._tabActivate=function(ui){var selectedTabIndex=this._selectTabs().tabs("option","active");if(selectedTabIndex==0)return;ui.newPanel.empty();this._idTextBox=null;this._nameTextBox=null;this._expressionTextBox=null;this._minTextBox=null;this._maxTextBox=null;this._measurementsList=null;if(!this._selectedDatasourceGroup)return;ui.newPanel.append(sprintf('<label for="computed-measurement-key-%1$s"><b>Id:</b></label> '+'<input id="computed-measurement-key-%1$s" class="ui-widget-content ui-corner-all" style="padding: 2px;" type="text"/>&nbsp;'+
'<label for="computed-measurement-name-%1$s"><b>Name:</b></label> '+'<input id="computed-measurement-name-%1$s" class="ui-widget-content ui-corner-all" style="padding: 2px;" type="text"/>'+"<br /><br />"+'<div id="computed-measurement-measurements-%1$s" style="overflow: auto; max-height: 200px; border-style: solid; border-width: 1px; border-color: #999999;"></div>'+"<br/>"+'<label for="computed-measurement-min-%1$s"><b>Min:</b></label> '+'<input id="computed-measurement-min-%1$s" class="ui-widget-content ui-corner-all" style="padding: 2px;" type="text"/>&nbsp;'+
'<label for="computed-measurement-max-%1$s"><b>Max:</b></label> '+'<input id="computed-measurement-max-%1$s" class="ui-widget-content ui-corner-all" style="padding: 2px;" type="text"/><br/>'+'<div style="overflow: hidden; padding: 10px; padding-right: 20px; margin: 0px;">'+'<textarea id="computed-measurement-expr-%1$s" class="ui-widget-content ui-corner-all" style="width: 100%%; height: 55px; padding: 5px; margin: 0; resize: none;"></textarea>'+"</div>",this._id));var msList=this._selectMeasurementsList();
var contents="";for(var i=0;i<this._datasourceGroupMeasurements.length;++i){var m=this._datasourceGroupMeasurements[i];var removeButton="";if(m.isComputed())removeButton='<button id="delete-button-%2$s-%3$s" data-measurement="%2$s">Delete %2$s</button>';contents+=sprintf('<div style="min-height: 30px; padding: 2px;">'+'<div style="margin: 6px; float: left;">%1$s {<b>%2$s</b>}</div>'+'<div style="float: right;">'+removeButton+'<button style="" id="measurement-button-%2$s-%3$s" data-measurement="%2$s">Insert %2$s</button>'+
"</div>"+"</div>",m.name(),i,this._id)}msList.append(contents);var self=this;for(i=0;i<this._datasourceGroupMeasurements.length;++i){m=this._datasourceGroupMeasurements[i];if(m.isComputed())$("#delete-button-"+i+"-"+this._id).button(this._deleteButtonsProperties).click(function(){self._deleteButtonClick($(this))});$("#measurement-button-"+i+"-"+this._id).button(this._addButtonProperties).click(function(){self._addButtonClick($(this))})}this._selectIdTextBox().watermark("[auto]");this._selectNameTextBox().watermark("[auto]");
this._selectMinTextBox().watermark("[auto]");this._selectMaxTextBox().watermark("[auto]");this._selectExpressionTextBox().watermark("[expression; for example: {0} - {1}]")};epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectDialog=function(){if(!this._dialog)this._dialog=$("#"+this._id);return this._dialog};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectExpressionTextBox=function(){if(!this._expressionTextBox)this._expressionTextBox=$("#computed-measurement-expr-"+this._id);return this._expressionTextBox};epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectIdTextBox=function(){if(!this._idTextBox)this._idTextBox=$("#computed-measurement-key-"+this._id);return this._idTextBox};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectNameTextBox=function(){if(!this._nameTextBox)this._nameTextBox=$("#computed-measurement-name-"+this._id);return this._nameTextBox};epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectMinTextBox=function(){if(!this._minTextBox)this._minTextBox=$("#computed-measurement-min-"+this._id);return this._minTextBox};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectMaxTextBox=function(){if(!this._maxTextBox)this._maxTextBox=$("#computed-measurement-max-"+this._id);return this._maxTextBox};epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectTabs=function(){if(!this._tabs)this._tabs=this._dialog.find(".computed-measurements-tabs");return this._tabs};
epiviz.ui.controls.ComputedMeasurementsDialog.prototype._selectMeasurementsList=function(){if(!this._measurementsList)this._measurementsList=$("#computed-measurement-measurements-"+this._id);return this._measurementsList};goog.provide("epiviz.ui.controls.CustomSettingsDialog");epiviz.ui.controls.CustomSettingsDialog=function(title,handlers,customSettingsDefs,customSettingsValues){epiviz.ui.controls.Dialog.call(this,title,handlers);this._customSettingsDefs=customSettingsDefs;this._customSettingsValues=epiviz.utils.mapCopy(customSettingsValues)};epiviz.ui.controls.CustomSettingsDialog.prototype=epiviz.utils.mapCopy(epiviz.ui.controls.Dialog.prototype);epiviz.ui.controls.CustomSettingsDialog.constructor=epiviz.ui.controls.CustomSettingsDialog;
epiviz.ui.controls.CustomSettingsDialog.prototype.show=function(){epiviz.ui.controls.Dialog.prototype.show.call(this);var SettingType=epiviz.ui.charts.CustomSetting.Type;if(!this._dialog){var self=this;this._dialog=$("#"+this._id);this._dialog.css("display","inline");var i,inputId,input,value;var content="";for(i=0;i<this._customSettingsDefs.length;++i){inputId=sprintf("%s-%s",this._id,this._customSettingsDefs[i].id);var row=sprintf('<tr><td><label for="%s">%s</label></td><td style="text-align: right;">%%s</td></tr>',
inputId,this._customSettingsDefs[i].label);input=null;value=this._customSettingsValues[this._customSettingsDefs[i].id];switch(this._customSettingsDefs[i].type){case SettingType.BOOLEAN:row=sprintf(row,sprintf('<div id="%1$s">'+'<label for="%1$s-true">On</label>'+'<input type="radio" id="%1$s-true" name="%1$s" %2$s />'+'<label for="%1$s-false">Off</label>'+'<input type="radio" id="%1$s-false" name="%1$s" %3$s />'+"</div>",inputId,value?'checked="checked"':"",value?"":'checked="checked"'));break;case SettingType.ARRAY:row=
sprintf(row,sprintf('<input id="%s" value="%s" class="ui-widget-content ui-corner-all" style="text-align: right; padding: 5px;" />',inputId,value.join(",")));break;case SettingType.NUMBER:case SettingType.STRING:row=sprintf(row,sprintf('<input id="%s" value="%s" class="ui-widget-content ui-corner-all" style="text-align: right; padding: 5px;" />',inputId,value));break;case SettingType.CATEGORICAL:var optionFormat='<option value="%1$s"%2$s>%1$s</option>';var options="";var def=this._customSettingsDefs[i];
if(def.possibleValues)for(var j=0;j<def.possibleValues.length;++j)options+=sprintf(optionFormat,def.possibleValues[j],def.possibleValues[j]==value?'selected="selected"':"");var selector=sprintf('<select id="%s">%s</select>',inputId,options);row=sprintf(row,selector);break}content+=row}content=sprintf('<div style="margin: 5px; padding: 5px; height: auto;"><table style="width: 100%%;">%s</table></div>',content);this._dialog.append(content);for(i=0;i<this._customSettingsDefs.length;++i){inputId=sprintf("%s-%s",
this._id,this._customSettingsDefs[i].id);input=$("#"+inputId);value=this._customSettingsValues[this._customSettingsDefs[i].id];switch(this._customSettingsDefs[i].type){case SettingType.BOOLEAN:input.buttonset();break;case SettingType.NUMBER:case SettingType.ARRAY:case SettingType.STRING:input.watermark(this._customSettingsDefs[i].label);break;case SettingType.CATEGORICAL:input.selectmenu()}}this._dialog.dialog({autoOpen:false,resizable:false,buttons:{Ok:function(){for(var i=0;i<self._customSettingsDefs.length;++i){inputId=
sprintf("%s-%s",self._id,self._customSettingsDefs[i].id);input=$("#"+inputId);var newValue=null;if(input.val()==epiviz.ui.charts.CustomSetting.DEFAULT)newValue=self._customSettingsDefs[i].defaultValue;else{var errorDialog=null;try{switch(self._customSettingsDefs[i].type){case SettingType.BOOLEAN:var checked=$("#"+inputId+" :radio:checked").attr("id");newValue=checked.substr(checked.lastIndexOf("-")+1)=="true";break;case SettingType.NUMBER:newValue=input.val()==epiviz.ui.charts.CustomSetting.DEFAULT?
self._customSettingsDefs[i].defaultValue:parseFloat(input.val());if(isNaN(newValue)){errorDialog=new epiviz.ui.controls.MessageDialog("Invalid property value",{Ok:function(){}},sprintf('Invalid value for setting "%s" (%s)',self._customSettingsDefs[i].label,self._customSettingsDefs[i].id),epiviz.ui.controls.MessageDialog.Icon.ERROR);errorDialog.show();return}break;case SettingType.ARRAY:newValue=input.val().split(/[\s,]+/g);break;case SettingType.STRING:case SettingType.CATEGORICAL:newValue=input.val();
break}}catch(error){errorDialog=new epiviz.ui.controls.MessageDialog("Invalid property value",{Ok:function(){}},sprintf('Invalid value for setting "%s" (%s)',self._customSettingsDefs[i].label,self._customSettingsDefs[i].id),epiviz.ui.controls.MessageDialog.Icon.ERROR);errorDialog.show();return}}self._customSettingsValues[self._customSettingsDefs[i].id]=newValue}self._handlers.ok(self._customSettingsValues);$(this).dialog("close")},Cancel:function(){self._handlers.cancel();$(this).dialog("close")}},
modal:true});this._dialog.dialog({close:function(event,ui){$(this).remove();self._dialog=null}})}this._dialog.dialog("open");this._dialog.dialog("option","position","center")};